version: '3.1'

services:
  db:
    image: postgres:16.1-alpine3.18
    container_name: gousers_postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_DB: ${DB_NAME} 

volumes:
  postgres:
