version: '3.1'

services:
  db:
    image: postgres:16.1-alpine3.18
    container_name: gousers_test_postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_DB: ${DB_NAME} 

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686
    environment:
      COLLECTOR_OTLP_ENABLED: true